import React, { createContext, useContext, useEffect, useState } from 'react';

export type LanguageCode = 'en' | 'es' | 'de' | 'ja';
export type CurrencyCode = 'USD' | 'EUR' | 'GBP' | 'JPY';

export const LANGUAGE_OPTIONS: { code: LanguageCode; label: string }[] = [
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Español' },
  { code: 'de', label: 'Deutsch' },
  { code: 'ja', label: '日本語' }
];

export const CURRENCY_OPTIONS: { code: CurrencyCode; label: string; symbol: string }[] = [
  { code: 'USD', label: 'USD ($)', symbol: '$' },
  { code: 'EUR', label: 'EUR (€)', symbol: '€' },
  { code: 'GBP', label: 'GBP (£)', symbol: '£' },
  { code: 'JPY', label: 'JPY (¥)', symbol: '¥' }
];

/**
 * Fixed, approximate conversion rates against USD.
 *
 * There is no live FX feed wired up, and the assets on this platform are
 * priced and traded in USDT regardless of display currency — this only
 * affects how portfolio totals are *shown* to the user, not what anything
 * actually trades at. Static rates are good enough for that and avoid
 * pulling in a paid FX API for a cosmetic feature.
 */
const CURRENCY_RATES: Record<CurrencyCode, number> = {
  USD: 1,
  EUR: 0.92,
  GBP: 0.79,
  JPY: 157
};

const CURRENCY_LOCALE: Record<CurrencyCode, string> = {
  USD: 'en-US',
  EUR: 'de-DE',
  GBP: 'en-GB',
  JPY: 'ja-JP'
};

type TranslationKey = keyof typeof TRANSLATIONS['en'];

const TRANSLATIONS = {
  en: {
    'nav.home': 'Home',
    'nav.markets': 'Markets',
    'nav.futures': 'Futures',
    'nav.spot': 'Spot',
    'nav.assets': 'Assets',

    'profile.signOut': 'Sign Out',
    'profile.practiceDemo': 'Practice Demo Workspace',
    'profile.verified': 'Level 2 Enterprise Verified',
    'profile.securityScoreTitle': 'Security Protection Score',
    'profile.highlySecured': 'HIGHLY SECURED',
    'profile.securityScoreDesc': 'Your account uses 2FA, Email Verification, Whitelisted Addresses, and Anti-Phishing protection.',

    'profile.suiteTitle': 'Account Security & Verification Suite',
    'profile.suiteDesc': 'Multi-tier authentication and anti-phishing protection',
    'profile.emailVerification': 'Email Verification',
    'profile.verifiedBadge': 'VERIFIED',
    'profile.emailNote': 'Required for all withdrawals and password changes.',
    'profile.googleAuth': 'Google Authenticator 2FA',
    'profile.active': 'ACTIVE',
    'profile.totpNote': 'TOTP Time-based Security Token Enabled',
    'profile.protectsNote': 'Protects funds from unauthorized withdrawals.',
    'profile.passkey': 'Biometric Passkey',
    'profile.hardwareReady': 'HARDWARE READY',
    'profile.passkeyNote': 'FaceID / TouchID / FIDO2 Key',
    'profile.nextGenNote': 'Next-gen passwordless security option.',

    'profile.antiPhishingTitle': 'Custom Anti-Phishing Code',
    'profile.antiPhishingDesc': 'This code will be embedded into every official notification email sent by Oriviant to prevent email spoofing and phishing.',
    'profile.changeCode': 'Change Code',
    'profile.saveCode': 'Save Code',
    'profile.protected': 'PROTECTED',

    'profile.trustedDevicesTitle': 'Trusted Device Management',
    'profile.trustedDevicesDesc': 'Active devices authorized to access your Oriviant wallet',
    'profile.currentDevice': 'CURRENT DEVICE',
    'profile.revokeSession': 'Revoke Session',

    'profile.loginActivityTitle': 'Recent Login Activity Logs',
    'profile.loginActivityDesc': 'Audit record of recent IP connections and device authorizations',
    'profile.dateTime': 'Date & Time',
    'profile.deviceBrowser': 'Device & Browser',
    'profile.location': 'Location',
    'profile.ipAddress': 'IP Address',
    'profile.status': 'Status',
    'profile.noLoginHistory': 'No login activity recorded yet.',

    'profile.preferencesTitle': 'Trading Preferences & Localization',
    'profile.themeMode': 'Theme Mode',
    'profile.darkTheme': 'Dark Theme',
    'profile.lightTheme': 'Light Theme',
    'profile.language': 'Language',
    'profile.displayCurrency': 'Display Currency',
    'profile.savePreferences': 'Save Preferences',
    'profile.preferencesSaved': 'Preferences updated successfully.',

    'profile.editName': 'Edit display name',
    'profile.changePicture': 'Change profile picture',
    'profile.save': 'Save',

    'common.signIn': 'Sign In',
    'common.register': 'Register',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.loading': 'Loading...',

    'header.copyTrading': 'Copy Trading',
    'header.academy': 'Academy',
    'header.reviews': 'Reviews',
    'header.practiceDemoMode': 'Practice Demo Mode',
    'header.searchPlaceholder': 'Search...',
    'header.searchTooltip': 'Search markets, coins, traders (Ctrl+K)',
    'header.search': 'Search',
    'header.notifications': 'Notifications',
    'header.accountProfile': 'Account Profile & Settings',
    'header.profileAccount': 'Profile & Account',
    'header.switchToLight': 'Switch to Light mode',
    'header.switchToDark': 'Switch to Dark mode',

    'drawer.accountManagement': 'Account Management',
    'drawer.closePanel': 'Close Account Panel',
    'drawer.accountUid': 'Account UID',
    'drawer.vipLevel': 'VIP Level',
    'drawer.verification': 'Verification',
    'drawer.kycLevel2': 'KYC Level 2',
    'drawer.securityStatus': 'Security Status',
    'drawer.twoFaActive': '2FA Active',
    'drawer.accountVerified': 'Account Verification: Verified',
    'drawer.dailyLimit': 'Daily Limit: $1,000,000',
    'drawer.themePreference': 'Theme Preference',
    'drawer.modeActive': 'Active',
    'drawer.toggleTheme': 'Toggle Theme',
    'drawer.quickActions': 'Quick Actions',
    'drawer.myProfile': 'My Profile',
    'drawer.myProfileDesc': 'Manage profile & identity details',
    'drawer.assets': 'Assets',
    'drawer.assetsDesc': 'Balances, deposit & withdrawal',
    'drawer.orders': 'Orders',
    'drawer.ordersDesc': 'Active trades & order history',
    'drawer.copyTradingDesc': 'Lead traders & copied portfolios',
    'drawer.settings': 'Settings',
    'drawer.settingsDesc': 'Platform & account configuration',
    'drawer.security': 'Security',
    'drawer.securityDesc': '2FA, passwords & API keys',
    'drawer.notificationsDesc': 'Price alerts & activity updates',
    'drawer.referralProgram': 'Referral Program (Earn 40%)',
    'drawer.referralDesc': 'Invite friends & track commission',
    'drawer.helpCenter': 'Help Center & Support',
    'drawer.helpDesc': '24/7 support & platform guides',
    'drawer.adminPortal': 'Admin Portal',
    'drawer.adminDesc': 'Restricted administrator access',
    'drawer.signOutFull': 'Sign Out of Oriviant Account',
    'drawer.welcomeExchange': 'Welcome to Oriviant Exchange',

    'mobileDrawer.tradingMarkets': 'TRADING & MARKETS',
    'mobileDrawer.homeOverview': 'Home Overview',
    'mobileDrawer.marketsOverview': 'Markets Overview',
    'mobileDrawer.spotTrading': 'Spot Trading',
    'mobileDrawer.futuresTrading': 'Futures Trading',
    'mobileDrawer.assetsWallets': 'Assets & Wallets',
    'mobileDrawer.rewardsEducation': 'REWARDS & EDUCATION',
    'mobileDrawer.referralHub': 'Referral Hub & Rewards',
    'mobileDrawer.earn40': 'Earn 40%',
    'mobileDrawer.cryptoAcademy': 'Crypto Academy & Guides',
    'mobileDrawer.platformReviews': 'Platform Reviews & Ratings',
    'mobileDrawer.accountSupport': 'ACCOUNT & SUPPORT',
    'mobileDrawer.userProfile': 'User Profile & Verification',
    'mobileDrawer.securitySettings': 'Security & Settings',
    'mobileDrawer.helpFaq': 'Help Center & FAQ',
    'mobileDrawer.adminControlPortal': 'Admin Control Portal',
    'mobileDrawer.builtForPerformance': 'Built for High Performance',

    'welcome.title': 'Welcome to Oriviant',
    'welcome.subtitle': 'Trade cryptocurrencies and global markets with a secure, fast, and professional trading platform.',
    'welcome.logIn': 'Log In',
    'welcome.createAccount': 'Create Account',
    'welcome.visitWebsite': 'Visit Website',
    'welcome.support': 'Support',
    'welcome.apkDownloaded': 'APK Downloaded! (v2.4.1)',
    'welcome.downloadingApk': 'Downloading APK...',
    'welcome.downloadLatestApk': 'Download Latest APK',
    'welcome.ecosystemPreview': 'ECOSYSTEM PREVIEW',
    'welcome.platformCapabilities': 'Platform Capabilities',
    'welcome.engineeredFor': 'Engineered for high-frequency execution, deep liquidity & institutional security',
    'welcome.explore': 'Explore',
    'welcome.realTimeData': 'REAL-TIME DATA',
    'welcome.liveMarketPreview': 'Live Market Preview',
    'welcome.guestsMayView': 'Guests may view live streaming prices across Crypto, Commodities, Forex & Stocks',
    'welcome.asset': 'Asset',
    'welcome.class': 'Class',
    'welcome.price': 'Price',
    'welcome.change24h': '24h Change',
    'welcome.sparkline': 'Sparkline',
    'welcome.action': 'Action',
    'welcome.trade': 'Trade',
    'welcome.reservesTitle': '100% Proof of Reserves & Cold Storage',
    'welcome.reservesDesc': 'All user assets backed 1:1 with real-time auditability and multi-sig security.',
    'welcome.joinToday': 'Join Oriviant Today',
    'welcome.loginRequired': 'Login Required',
    'welcome.loginRequiredPrefix': 'Sign in or create an account to access',
    'welcome.loginRequiredSuffix': 'on Oriviant.',
    'welcome.tradingFeatures': 'trading features',

    'assetClass.crypto': 'Crypto',
    'assetClass.commodities': 'Commodities',
    'assetClass.forex': 'Forex',
    'assetClass.stocks': 'Stocks',

    'welcome.feat1Title': 'Spot Trading',
    'welcome.feat1Badge': '0.01% Fees',
    'welcome.feat1Desc': 'Lightning-fast spot execution on 200+ crypto & fiat pairs with institutional depth.',
    'welcome.feat2Title': 'Futures Trading',
    'welcome.feat2Badge': 'Up to 125x',
    'welcome.feat2Desc': 'Perpetual contracts with cross/isolated margin, sub-millisecond risk engine.',
    'welcome.feat3Title': 'Practice Mode',
    'welcome.feat3Badge': '$10,000 USDT',
    'welcome.feat3Desc': 'Risk-free paper trading desk with live real-time market feeds & virtual ledger.',
    'welcome.feat4Title': 'Copy Trading',
    'welcome.feat4Badge': 'Automated PnL',
    'welcome.feat4Desc': 'Automatically mirror top-ranked lead traders or share strategies to earn 40% profit share.',
    'welcome.feat5Title': 'Academy',
    'welcome.feat5Badge': 'Free Guides',
    'welcome.feat5Desc': 'Master technical analysis, risk management & derivative trading frameworks.',
    'welcome.feat6Title': 'Secure Wallet',
    'welcome.feat6Badge': 'Cold Storage',
    'welcome.feat6Desc': 'Multi-signature custody, anti-phishing protection & 2FA account safety.',
    'welcome.feat7Title': 'Real-Time Markets',
    'welcome.feat7Badge': 'Sub-ms Ticks',
    'welcome.feat7Desc': 'Stream order books, depth charts, and trade feeds across global asset classes.',
    'welcome.feat8Title': 'Advanced Charts',
    'welcome.feat8Badge': 'TradingView',
    'welcome.feat8Desc': '100+ technical indicators, drawing tools, and multi-timeframe analytics.',

    'home.spotTrading': 'Spot Trading',
    'home.futures125x': 'Futures 125x',
    'home.demoMode': 'Demo Mode',
    'home.referralHub': 'Referral Hub',
    'home.fearGreedIndex': 'Crypto Fear & Greed Index',
    'home.updatedAgo': 'Updated 1h ago',
    'home.extremeGreed': 'Extreme Greed',
    'home.sentimentDesc': 'Market sentiment is strongly bullish. Traders are aggressively adding long exposure across Layer 1 and AI tokens.',
    'home.topGainers': 'Top 24h Gainers',
    'home.viewAll': 'View All',
    'home.volumeLeaders': '24h Volume Leaders',
    'home.proCopyTrading': 'PRO COPY TRADING',
    'home.automateProfits': 'Automate Profits with Top Lead Traders',
    'home.copyTradesDesc': 'Copy trades 1:1 automatically. No manual execution required.',
    'home.exploreLeadTraders': 'Explore All Lead Traders',
    'home.copiers': 'Copiers',
    'home.risk': 'Risk',
    'home.winRate': 'Win Rate',
    'home.aum': 'AUM',
    'home.copyThisTrader': 'Copy This Trader',

    'markets.title': 'Multi-Asset Marketplace',
    'markets.subtitle': 'Real-time quotes across Crypto, Forex, Stocks, ETFs, Indices, Commodities & Bonds.',
    'markets.searchPlaceholder': 'Search symbol, name or market (e.g. AAPL, EUR/USD, Gold)',
    'markets.liveFeedConnected': 'LIVE DATA FEED CONNECTED',
    'markets.latency': 'Latency',
    'markets.streaming': 'Streaming',
    'markets.markets': 'Markets',
    'markets.syncEngine': 'Sync Engine',
    'markets.lastSync': 'Last Sync',
    'markets.syncFeedNow': 'Sync Feed Now',
    'markets.catAll': 'All Markets',
    'markets.catWatchlist': '★ Watchlist',
    'markets.catCrypto': 'Crypto',
    'markets.catForex': 'Forex',
    'markets.catStocks': 'Stocks',
    'markets.catEtfs': 'ETFs',
    'markets.catIndices': 'Indices',
    'markets.catCommodities': 'Commodities',
    'markets.catMetals': 'Metals',
    'markets.catEnergy': 'Energy',
    'markets.catBonds': 'Bonds',
    'markets.catTrending': '🔥 Trending',
    'markets.catGainers': '📈 Top Gainers',
    'markets.catLosers': '📉 Top Losers',
    'markets.catNew': '✨ New Listings',
    'markets.catTraded': '⚡ Most Traded',
    'markets.tradingPair': 'Trading Pair',
    'markets.priceUsdt': 'Price (USDT)',
    'markets.change24h': '24h Change',
    'markets.volume24h': '24h Volume',
    'markets.sparkline7d': 'Sparkline (7D)',
    'markets.actions': 'Actions',
    'markets.noCoinsFound': 'No coins found matching',
    'markets.spot': 'Spot',
    'markets.futures': 'Futures',

    'auth.welcomeBack': 'Welcome Back to Oriviant',
    'auth.resetPassword': 'Reset Your Password',
    'auth.verify2fa': 'Verify 2FA Security Code',
    'auth.createPin': 'Create Quick Access PIN',
    'auth.loginSubtitle': 'Access institutional liquidity & 125x perp futures',
    'auth.forgotSubtitle': 'Enter your email to receive recovery instructions',
    'auth.otpSubtitle': 'Enter the 6-digit verification code sent to your device',
    'auth.pinSubtitle': 'Set a 4-digit security PIN for biometric quick sign-in',
    'auth.emailAddress': 'Email Address',
    'auth.password': 'Password',
    'auth.forgot': 'Forgot?',
    'auth.rememberMe': 'Remember my session on this device',
    'auth.authenticating': 'Authenticating...',
    'auth.signInToAccount': 'Sign In to Account',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.verifySecurityCode': 'Verify Security Code',
    'auth.saveSecurityPin': 'Save Security PIN',
    'auth.or': 'OR',
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.noAccount': "Don't have an Oriviant account?",
    'auth.signUp': 'Sign Up',
    'auth.closeModal': 'Close authentication modal',
    'auth.showPassword': 'Show password',
    'auth.hidePassword': 'Hide password',

    'signup.exchange': 'ORIVIANT EXCHANGE',
    'signup.createAccount': 'Create Your Account',
    'signup.tagline': 'Trade • Invest • Grow',
    'signup.joinDesc': 'Join thousands of traders worldwide and start your trading journey today.',
    'signup.fullName': 'Full Name',
    'signup.fullNameRequired': 'Full name is required',
    'signup.fullNameMin': 'Minimum 2 characters required',
    'signup.emailRequired': 'Email address is required',
    'signup.emailInvalid': 'Please enter a valid email address',
    'signup.emailTaken': 'This email address is already registered.',
    'signup.phoneNumber': 'Phone Number',
    'signup.autoDetected': 'Auto-detected',
    'signup.phoneRequired': 'Phone number is required',
    'signup.phoneInvalid': 'Please enter a valid phone number',
    'signup.phoneTaken': 'This phone number is already registered.',
    'signup.searchCountry': 'Search country or code...',
    'signup.noMatchingCountry': 'No matching country',
    'signup.password': 'Password',
    'signup.strength': 'Strength',
    'signup.strengthWeak': 'Weak',
    'signup.strengthFair': 'Fair',
    'signup.strengthGood': 'Good',
    'signup.strengthStrong': 'Strong',
    'signup.min8Chars': 'Min 8 characters',
    'signup.uppercaseLetter': 'Uppercase letter',
    'signup.lowercaseLetter': 'Lowercase letter',
    'signup.oneNumber': 'One number',
    'signup.oneSpecialChar': 'One special character (!@#$%)',
    'signup.confirmPassword': 'Confirm Password',
    'signup.passwordsMatch': 'Passwords Match',
    'signup.passwordsNoMatch': 'Passwords Do Not Match',
    'signup.reenterPassword': 'Re-enter password',
    'signup.haveReferralCode': 'Have a Referral Code?',
    'signup.enterCode': 'Enter Code (e.g. ORV894)',
    'signup.referralBonus': 'Receive 10% fee discount and bonus $100 trading voucher on deposit.',
    'signup.imHuman': 'I am human (Security Verification)',
    'signup.agreeTermsPrefix': 'I agree to the',
    'signup.termsOfService': 'Terms of Service',
    'signup.and': 'and',
    'signup.privacyPolicy': 'Privacy Policy',
    'signup.receiveUpdates': 'Receive trading updates, platform news, and promotions.',
    'signup.creatingAccount': 'Creating Account...',
    'signup.alreadyHaveAccount': 'Already have an account?',
    'signup.registrationFailed': 'Registration failed. The email might already be in use or the server is unreachable.',
    'signup.accountCreated': 'Account Created Successfully!',
    'signup.verificationSentPrefix': "We've sent a verification email to",
    'signup.verificationSentSuffix': 'Please verify your email before accessing your account.',
    'signup.verificationInstructions': 'Verification Instructions',
    'signup.instructionsLine1': '1. Check your email inbox for the message from Oriviant Security.',
    'signup.instructionsLine2': '2. Click the secure verification link inside.',
    'signup.instructionsLine3': '3. Return here or proceed to log in to access your $10,000 USDT practice balance and live markets.',
    'signup.openEmailApp': 'Open Email App',
    'signup.resendEmail': 'Resend Email',
    'signup.resendCountdown': 'Resend',
    'signup.changeEmail': 'Change Email',
    'signup.proceedToLogin': 'Proceed to Sign In & Dashboard',
    'signup.resendDispatched': 'A new verification email has been dispatched!',

    'wallet.vaultBadge': 'ORIVIANT ENTERPRISE VAULT',
    'wallet.frozen': 'WALLET FROZEN',
    'wallet.title': 'Wallet & Asset Management',
    'wallet.subtitle': 'Multi-chain deposits, institutional cold-storage withdrawals & internal transfers.',
    'wallet.deposit': 'Deposit',
    'wallet.withdraw': 'Withdraw',
    'wallet.transfer': 'Transfer',
    'wallet.addressBook': 'Address Book',
    'wallet.balance': 'BALANCE',
    'wallet.totalAvailable': 'Total Available',
    'wallet.readyForTrading': 'Ready for trading / withdrawal',
    'wallet.lockedFrozen': 'Locked / Frozen',
    'wallet.pendingOrders': 'Pending orders & withdrawals',
    'wallet.unrealizedPnl': 'Unrealized PnL',
    'wallet.openFuturesPositions': 'Open Futures positions',
    'wallet.accountTier': 'Account Tier',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.markets': 'Mercados',
    'nav.futures': 'Futuros',
    'nav.spot': 'Spot',
    'nav.assets': 'Activos',

    'profile.signOut': 'Cerrar Sesión',
    'profile.practiceDemo': 'Espacio de Práctica Demo',
    'profile.verified': 'Nivel 2 Empresarial Verificado',
    'profile.securityScoreTitle': 'Puntuación de Seguridad',
    'profile.highlySecured': 'ALTAMENTE SEGURO',
    'profile.securityScoreDesc': 'Tu cuenta usa 2FA, verificación por correo, direcciones de lista blanca y protección anti-phishing.',

    'profile.suiteTitle': 'Suite de Seguridad y Verificación de Cuenta',
    'profile.suiteDesc': 'Autenticación multinivel y protección anti-phishing',
    'profile.emailVerification': 'Verificación de Correo',
    'profile.verifiedBadge': 'VERIFICADO',
    'profile.emailNote': 'Requerido para todos los retiros y cambios de contraseña.',
    'profile.googleAuth': 'Google Authenticator 2FA',
    'profile.active': 'ACTIVO',
    'profile.totpNote': 'Token de seguridad TOTP habilitado',
    'profile.protectsNote': 'Protege los fondos contra retiros no autorizados.',
    'profile.passkey': 'Llave de Acceso Biométrica',
    'profile.hardwareReady': 'HARDWARE LISTO',
    'profile.passkeyNote': 'FaceID / TouchID / Llave FIDO2',
    'profile.nextGenNote': 'Opción de seguridad sin contraseña de próxima generación.',

    'profile.antiPhishingTitle': 'Código Anti-Phishing Personalizado',
    'profile.antiPhishingDesc': 'Este código se incluirá en cada correo oficial enviado por Oriviant para prevenir la suplantación y el phishing.',
    'profile.changeCode': 'Cambiar Código',
    'profile.saveCode': 'Guardar Código',
    'profile.protected': 'PROTEGIDO',

    'profile.trustedDevicesTitle': 'Gestión de Dispositivos de Confianza',
    'profile.trustedDevicesDesc': 'Dispositivos activos autorizados para acceder a tu billetera Oriviant',
    'profile.currentDevice': 'DISPOSITIVO ACTUAL',
    'profile.revokeSession': 'Revocar Sesión',

    'profile.loginActivityTitle': 'Registro de Actividad de Inicio de Sesión',
    'profile.loginActivityDesc': 'Registro de auditoría de conexiones IP y autorizaciones de dispositivos recientes',
    'profile.dateTime': 'Fecha y Hora',
    'profile.deviceBrowser': 'Dispositivo y Navegador',
    'profile.location': 'Ubicación',
    'profile.ipAddress': 'Dirección IP',
    'profile.status': 'Estado',
    'profile.noLoginHistory': 'Aún no hay actividad de inicio de sesión registrada.',

    'profile.preferencesTitle': 'Preferencias de Trading y Localización',
    'profile.themeMode': 'Modo de Tema',
    'profile.darkTheme': 'Tema Oscuro',
    'profile.lightTheme': 'Tema Claro',
    'profile.language': 'Idioma',
    'profile.displayCurrency': 'Moneda de Visualización',
    'profile.savePreferences': 'Guardar Preferencias',
    'profile.preferencesSaved': 'Preferencias actualizadas correctamente.',

    'profile.editName': 'Editar nombre para mostrar',
    'profile.changePicture': 'Cambiar foto de perfil',
    'profile.save': 'Guardar',

    'common.signIn': 'Iniciar Sesión',
    'common.register': 'Registrarse',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.close': 'Cerrar',
    'common.loading': 'Cargando...',

    'header.copyTrading': 'Copy Trading',
    'header.academy': 'Academia',
    'header.reviews': 'Reseñas',
    'header.practiceDemoMode': 'Modo Demo de Práctica',
    'header.searchPlaceholder': 'Buscar...',
    'header.searchTooltip': 'Buscar mercados, monedas, traders (Ctrl+K)',
    'header.search': 'Buscar',
    'header.notifications': 'Notificaciones',
    'header.accountProfile': 'Perfil de Cuenta y Configuración',
    'header.profileAccount': 'Perfil y Cuenta',
    'header.switchToLight': 'Cambiar a modo Claro',
    'header.switchToDark': 'Cambiar a modo Oscuro',

    'drawer.accountManagement': 'Gestión de Cuenta',
    'drawer.closePanel': 'Cerrar Panel de Cuenta',
    'drawer.accountUid': 'UID de Cuenta',
    'drawer.vipLevel': 'Nivel VIP',
    'drawer.verification': 'Verificación',
    'drawer.kycLevel2': 'KYC Nivel 2',
    'drawer.securityStatus': 'Estado de Seguridad',
    'drawer.twoFaActive': '2FA Activo',
    'drawer.accountVerified': 'Verificación de Cuenta: Verificada',
    'drawer.dailyLimit': 'Límite Diario: $1,000,000',
    'drawer.themePreference': 'Preferencia de Tema',
    'drawer.modeActive': 'Activo',
    'drawer.toggleTheme': 'Cambiar Tema',
    'drawer.quickActions': 'Acciones Rápidas',
    'drawer.myProfile': 'Mi Perfil',
    'drawer.myProfileDesc': 'Gestiona tu perfil y datos de identidad',
    'drawer.assets': 'Activos',
    'drawer.assetsDesc': 'Saldos, depósitos y retiros',
    'drawer.orders': 'Órdenes',
    'drawer.ordersDesc': 'Operaciones activas e historial',
    'drawer.copyTradingDesc': 'Traders líderes y carteras copiadas',
    'drawer.settings': 'Configuración',
    'drawer.settingsDesc': 'Configuración de plataforma y cuenta',
    'drawer.security': 'Seguridad',
    'drawer.securityDesc': '2FA, contraseñas y claves API',
    'drawer.notificationsDesc': 'Alertas de precio y actividad',
    'drawer.referralProgram': 'Programa de Referidos (Gana 40%)',
    'drawer.referralDesc': 'Invita amigos y sigue tus comisiones',
    'drawer.helpCenter': 'Centro de Ayuda y Soporte',
    'drawer.helpDesc': 'Soporte 24/7 y guías de la plataforma',
    'drawer.adminPortal': 'Portal de Administración',
    'drawer.adminDesc': 'Acceso restringido para administradores',
    'drawer.signOutFull': 'Cerrar Sesión de la Cuenta Oriviant',
    'drawer.welcomeExchange': 'Bienvenido a Oriviant Exchange',

    'mobileDrawer.tradingMarkets': 'TRADING Y MERCADOS',
    'mobileDrawer.homeOverview': 'Resumen de Inicio',
    'mobileDrawer.marketsOverview': 'Resumen de Mercados',
    'mobileDrawer.spotTrading': 'Trading Spot',
    'mobileDrawer.futuresTrading': 'Trading de Futuros',
    'mobileDrawer.assetsWallets': 'Activos y Billeteras',
    'mobileDrawer.rewardsEducation': 'RECOMPENSAS Y EDUCACIÓN',
    'mobileDrawer.referralHub': 'Centro de Referidos y Recompensas',
    'mobileDrawer.earn40': 'Gana 40%',
    'mobileDrawer.cryptoAcademy': 'Academia Cripto y Guías',
    'mobileDrawer.platformReviews': 'Reseñas y Calificaciones',
    'mobileDrawer.accountSupport': 'CUENTA Y SOPORTE',
    'mobileDrawer.userProfile': 'Perfil de Usuario y Verificación',
    'mobileDrawer.securitySettings': 'Seguridad y Configuración',
    'mobileDrawer.helpFaq': 'Centro de Ayuda y FAQ',
    'mobileDrawer.adminControlPortal': 'Portal de Control Admin',
    'mobileDrawer.builtForPerformance': 'Diseñado para Alto Rendimiento',

    'welcome.title': 'Bienvenido a Oriviant',
    'welcome.subtitle': 'Opera criptomonedas y mercados globales con una plataforma segura, rápida y profesional.',
    'welcome.logIn': 'Iniciar Sesión',
    'welcome.createAccount': 'Crear Cuenta',
    'welcome.visitWebsite': 'Visitar Sitio Web',
    'welcome.support': 'Soporte',
    'welcome.apkDownloaded': '¡APK Descargado! (v2.4.1)',
    'welcome.downloadingApk': 'Descargando APK...',
    'welcome.downloadLatestApk': 'Descargar Último APK',
    'welcome.ecosystemPreview': 'VISTA PREVIA DEL ECOSISTEMA',
    'welcome.platformCapabilities': 'Capacidades de la Plataforma',
    'welcome.engineeredFor': 'Diseñado para ejecución de alta frecuencia, liquidez profunda y seguridad institucional',
    'welcome.explore': 'Explorar',
    'welcome.realTimeData': 'DATOS EN TIEMPO REAL',
    'welcome.liveMarketPreview': 'Vista Previa de Mercado en Vivo',
    'welcome.guestsMayView': 'Los invitados pueden ver precios en vivo de Cripto, Materias Primas, Forex y Acciones',
    'welcome.asset': 'Activo',
    'welcome.class': 'Clase',
    'welcome.price': 'Precio',
    'welcome.change24h': 'Cambio 24h',
    'welcome.sparkline': 'Gráfico',
    'welcome.action': 'Acción',
    'welcome.trade': 'Operar',
    'welcome.reservesTitle': '100% Prueba de Reservas y Almacenamiento en Frío',
    'welcome.reservesDesc': 'Todos los activos de usuarios están respaldados 1:1 con auditoría en tiempo real y seguridad multi-firma.',
    'welcome.joinToday': 'Únete a Oriviant Hoy',
    'welcome.loginRequired': 'Inicio de Sesión Requerido',
    'welcome.loginRequiredPrefix': 'Inicia sesión o crea una cuenta para acceder a',
    'welcome.loginRequiredSuffix': 'en Oriviant.',
    'welcome.tradingFeatures': 'funciones de trading',

    'assetClass.crypto': 'Cripto',
    'assetClass.commodities': 'Materias Primas',
    'assetClass.forex': 'Forex',
    'assetClass.stocks': 'Acciones',

    'welcome.feat1Title': 'Trading Spot',
    'welcome.feat1Badge': '0.01% Comisión',
    'welcome.feat1Desc': 'Ejecución spot ultrarrápida en más de 200 pares cripto y fiat con profundidad institucional.',
    'welcome.feat2Title': 'Trading de Futuros',
    'welcome.feat2Badge': 'Hasta 125x',
    'welcome.feat2Desc': 'Contratos perpetuos con margen cruzado/aislado y motor de riesgo de submilisegundos.',
    'welcome.feat3Title': 'Modo de Práctica',
    'welcome.feat3Badge': '$10,000 USDT',
    'welcome.feat3Desc': 'Mesa de trading simulado sin riesgo con datos de mercado en vivo y libro contable virtual.',
    'welcome.feat4Title': 'Copy Trading',
    'welcome.feat4Badge': 'PnL Automatizado',
    'welcome.feat4Desc': 'Copia automáticamente a los mejores traders o comparte estrategias para ganar el 40% de las ganancias.',
    'welcome.feat5Title': 'Academia',
    'welcome.feat5Badge': 'Guías Gratis',
    'welcome.feat5Desc': 'Domina el análisis técnico, gestión de riesgo y estrategias de derivados.',
    'welcome.feat6Title': 'Billetera Segura',
    'welcome.feat6Badge': 'Almacenamiento en Frío',
    'welcome.feat6Desc': 'Custodia multi-firma, protección anti-phishing y seguridad 2FA.',
    'welcome.feat7Title': 'Mercados en Tiempo Real',
    'welcome.feat7Badge': 'Ticks de Submilisegundos',
    'welcome.feat7Desc': 'Transmite libros de órdenes, gráficos de profundidad y feeds de operaciones globales.',
    'welcome.feat8Title': 'Gráficos Avanzados',
    'welcome.feat8Badge': 'TradingView',
    'welcome.feat8Desc': 'Más de 100 indicadores técnicos, herramientas de dibujo y análisis multi-temporal.',

    'home.spotTrading': 'Trading Spot',
    'home.futures125x': 'Futuros 125x',
    'home.demoMode': 'Modo Demo',
    'home.referralHub': 'Centro de Referidos',
    'home.fearGreedIndex': 'Índice de Miedo y Codicia Cripto',
    'home.updatedAgo': 'Actualizado hace 1h',
    'home.extremeGreed': 'Codicia Extrema',
    'home.sentimentDesc': 'El sentimiento del mercado es fuertemente alcista. Los traders están aumentando agresivamente su exposición larga en tokens Layer 1 e IA.',
    'home.topGainers': 'Top Ganadores 24h',
    'home.viewAll': 'Ver Todo',
    'home.volumeLeaders': 'Líderes de Volumen 24h',
    'home.proCopyTrading': 'COPY TRADING PRO',
    'home.automateProfits': 'Automatiza Ganancias con los Mejores Traders',
    'home.copyTradesDesc': 'Copia operaciones 1:1 automáticamente. No requiere ejecución manual.',
    'home.exploreLeadTraders': 'Explorar Todos los Traders Líderes',
    'home.copiers': 'Copiadores',
    'home.risk': 'Riesgo',
    'home.winRate': 'Tasa de Éxito',
    'home.aum': 'AUM',
    'home.copyThisTrader': 'Copiar a Este Trader',

    'markets.title': 'Mercado Multi-Activos',
    'markets.subtitle': 'Cotizaciones en tiempo real de Cripto, Forex, Acciones, ETFs, Índices, Materias Primas y Bonos.',
    'markets.searchPlaceholder': 'Buscar símbolo, nombre o mercado (ej. AAPL, EUR/USD, Oro)',
    'markets.liveFeedConnected': 'FEED DE DATOS EN VIVO CONECTADO',
    'markets.latency': 'Latencia',
    'markets.streaming': 'Transmitiendo',
    'markets.markets': 'Mercados',
    'markets.syncEngine': 'Motor de Sincronización',
    'markets.lastSync': 'Última Sincronización',
    'markets.syncFeedNow': 'Sincronizar Ahora',
    'markets.catAll': 'Todos los Mercados',
    'markets.catWatchlist': '★ Lista de Seguimiento',
    'markets.catCrypto': 'Cripto',
    'markets.catForex': 'Forex',
    'markets.catStocks': 'Acciones',
    'markets.catEtfs': 'ETFs',
    'markets.catIndices': 'Índices',
    'markets.catCommodities': 'Materias Primas',
    'markets.catMetals': 'Metales',
    'markets.catEnergy': 'Energía',
    'markets.catBonds': 'Bonos',
    'markets.catTrending': '🔥 Tendencias',
    'markets.catGainers': '📈 Top Ganadores',
    'markets.catLosers': '📉 Top Perdedores',
    'markets.catNew': '✨ Nuevos Listados',
    'markets.catTraded': '⚡ Más Operados',
    'markets.tradingPair': 'Par de Trading',
    'markets.priceUsdt': 'Precio (USDT)',
    'markets.change24h': 'Cambio 24h',
    'markets.volume24h': 'Volumen 24h',
    'markets.sparkline7d': 'Gráfico (7D)',
    'markets.actions': 'Acciones',
    'markets.noCoinsFound': 'No se encontraron monedas que coincidan con',
    'markets.spot': 'Spot',
    'markets.futures': 'Futuros',

    'auth.welcomeBack': 'Bienvenido de Nuevo a Oriviant',
    'auth.resetPassword': 'Restablece tu Contraseña',
    'auth.verify2fa': 'Verificar Código de Seguridad 2FA',
    'auth.createPin': 'Crear PIN de Acceso Rápido',
    'auth.loginSubtitle': 'Accede a liquidez institucional y futuros perpetuos 125x',
    'auth.forgotSubtitle': 'Ingresa tu correo para recibir instrucciones de recuperación',
    'auth.otpSubtitle': 'Ingresa el código de 6 dígitos enviado a tu dispositivo',
    'auth.pinSubtitle': 'Configura un PIN de 4 dígitos para inicio de sesión biométrico rápido',
    'auth.emailAddress': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.forgot': '¿Olvidaste?',
    'auth.rememberMe': 'Recordar mi sesión en este dispositivo',
    'auth.authenticating': 'Autenticando...',
    'auth.signInToAccount': 'Iniciar Sesión',
    'auth.sendResetLink': 'Enviar Enlace de Restablecimiento',
    'auth.verifySecurityCode': 'Verificar Código de Seguridad',
    'auth.saveSecurityPin': 'Guardar PIN de Seguridad',
    'auth.or': 'O',
    'auth.continueWithGoogle': 'Continuar con Google',
    'auth.noAccount': '¿No tienes una cuenta Oriviant?',
    'auth.signUp': 'Regístrate',
    'auth.closeModal': 'Cerrar ventana de autenticación',
    'auth.showPassword': 'Mostrar contraseña',
    'auth.hidePassword': 'Ocultar contraseña',

    'signup.exchange': 'ORIVIANT EXCHANGE',
    'signup.createAccount': 'Crea Tu Cuenta',
    'signup.tagline': 'Trade • Invest • Grow',
    'signup.joinDesc': 'Únete a miles de traders en todo el mundo y comienza tu viaje de trading hoy.',
    'signup.fullName': 'Nombre Completo',
    'signup.fullNameRequired': 'El nombre completo es obligatorio',
    'signup.fullNameMin': 'Se requieren al menos 2 caracteres',
    'signup.emailRequired': 'El correo electrónico es obligatorio',
    'signup.emailInvalid': 'Por favor ingresa un correo electrónico válido',
    'signup.emailTaken': 'Este correo electrónico ya está registrado.',
    'signup.phoneNumber': 'Número de Teléfono',
    'signup.autoDetected': 'Detectado automáticamente',
    'signup.phoneRequired': 'El número de teléfono es obligatorio',
    'signup.phoneInvalid': 'Por favor ingresa un número de teléfono válido',
    'signup.phoneTaken': 'Este número de teléfono ya está registrado.',
    'signup.searchCountry': 'Buscar país o código...',
    'signup.noMatchingCountry': 'No se encontró el país',
    'signup.password': 'Contraseña',
    'signup.strength': 'Fortaleza',
    'signup.strengthWeak': 'Débil',
    'signup.strengthFair': 'Regular',
    'signup.strengthGood': 'Buena',
    'signup.strengthStrong': 'Fuerte',
    'signup.min8Chars': 'Mínimo 8 caracteres',
    'signup.uppercaseLetter': 'Letra mayúscula',
    'signup.lowercaseLetter': 'Letra minúscula',
    'signup.oneNumber': 'Un número',
    'signup.oneSpecialChar': 'Un carácter especial (!@#$%)',
    'signup.confirmPassword': 'Confirmar Contraseña',
    'signup.passwordsMatch': 'Las Contraseñas Coinciden',
    'signup.passwordsNoMatch': 'Las Contraseñas No Coinciden',
    'signup.reenterPassword': 'Vuelve a ingresar la contraseña',
    'signup.haveReferralCode': '¿Tienes un Código de Referido?',
    'signup.enterCode': 'Ingresa el Código (ej. ORV894)',
    'signup.referralBonus': 'Recibe 10% de descuento en comisiones y un bono de $100 en tu depósito.',
    'signup.imHuman': 'Soy humano (Verificación de Seguridad)',
    'signup.agreeTermsPrefix': 'Acepto los',
    'signup.termsOfService': 'Términos de Servicio',
    'signup.and': 'y la',
    'signup.privacyPolicy': 'Política de Privacidad',
    'signup.receiveUpdates': 'Recibir actualizaciones de trading, noticias de la plataforma y promociones.',
    'signup.creatingAccount': 'Creando Cuenta...',
    'signup.alreadyHaveAccount': '¿Ya tienes una cuenta?',
    'signup.registrationFailed': 'Registro fallido. El correo puede que ya esté en uso o el servidor no está disponible.',
    'signup.accountCreated': '¡Cuenta Creada Exitosamente!',
    'signup.verificationSentPrefix': 'Hemos enviado un correo de verificación a',
    'signup.verificationSentSuffix': 'Por favor verifica tu correo antes de acceder a tu cuenta.',
    'signup.verificationInstructions': 'Instrucciones de Verificación',
    'signup.instructionsLine1': '1. Revisa tu bandeja de entrada por el mensaje de Oriviant Security.',
    'signup.instructionsLine2': '2. Haz clic en el enlace de verificación seguro dentro del correo.',
    'signup.instructionsLine3': '3. Vuelve aquí o inicia sesión para acceder a tu saldo de práctica de $10,000 USDT y mercados en vivo.',
    'signup.openEmailApp': 'Abrir App de Correo',
    'signup.resendEmail': 'Reenviar Correo',
    'signup.resendCountdown': 'Reenviar',
    'signup.changeEmail': 'Cambiar Correo',
    'signup.proceedToLogin': 'Continuar a Iniciar Sesión y Panel',
    'signup.resendDispatched': '¡Se ha enviado un nuevo correo de verificación!',

    'wallet.vaultBadge': 'BÓVEDA EMPRESARIAL ORIVIANT',
    'wallet.frozen': 'BILLETERA CONGELADA',
    'wallet.title': 'Gestión de Billetera y Activos',
    'wallet.subtitle': 'Depósitos multi-cadena, retiros institucionales en frío y transferencias internas.',
    'wallet.deposit': 'Depositar',
    'wallet.withdraw': 'Retirar',
    'wallet.transfer': 'Transferir',
    'wallet.addressBook': 'Libreta de Direcciones',
    'wallet.balance': 'SALDO',
    'wallet.totalAvailable': 'Total Disponible',
    'wallet.readyForTrading': 'Listo para trading / retiro',
    'wallet.lockedFrozen': 'Bloqueado / Congelado',
    'wallet.pendingOrders': 'Órdenes y retiros pendientes',
    'wallet.unrealizedPnl': 'PnL No Realizado',
    'wallet.openFuturesPositions': 'Posiciones de Futuros Abiertas',
    'wallet.accountTier': 'Nivel de Cuenta',
  },
  de: {
    'nav.home': 'Start',
    'nav.markets': 'Märkte',
    'nav.futures': 'Futures',
    'nav.spot': 'Spot',
    'nav.assets': 'Vermögen',

    'profile.signOut': 'Abmelden',
    'profile.practiceDemo': 'Demo-Übungsbereich',
    'profile.verified': 'Level 2 Enterprise Verifiziert',
    'profile.securityScoreTitle': 'Sicherheitsbewertung',
    'profile.highlySecured': 'STARK GESICHERT',
    'profile.securityScoreDesc': 'Ihr Konto nutzt 2FA, E-Mail-Verifizierung, Whitelist-Adressen und Anti-Phishing-Schutz.',

    'profile.suiteTitle': 'Konto-Sicherheits- und Verifizierungspaket',
    'profile.suiteDesc': 'Mehrstufige Authentifizierung und Anti-Phishing-Schutz',
    'profile.emailVerification': 'E-Mail-Verifizierung',
    'profile.verifiedBadge': 'VERIFIZIERT',
    'profile.emailNote': 'Erforderlich für alle Auszahlungen und Passwortänderungen.',
    'profile.googleAuth': 'Google Authenticator 2FA',
    'profile.active': 'AKTIV',
    'profile.totpNote': 'TOTP-Sicherheitstoken aktiviert',
    'profile.protectsNote': 'Schützt Guthaben vor unautorisierten Auszahlungen.',
    'profile.passkey': 'Biometrischer Passkey',
    'profile.hardwareReady': 'HARDWARE BEREIT',
    'profile.passkeyNote': 'FaceID / TouchID / FIDO2-Schlüssel',
    'profile.nextGenNote': 'Passwortlose Sicherheitsoption der nächsten Generation.',

    'profile.antiPhishingTitle': 'Individueller Anti-Phishing-Code',
    'profile.antiPhishingDesc': 'Dieser Code wird in jede offizielle Benachrichtigungs-E-Mail von Oriviant eingebettet, um E-Mail-Spoofing und Phishing zu verhindern.',
    'profile.changeCode': 'Code Ändern',
    'profile.saveCode': 'Code Speichern',
    'profile.protected': 'GESCHÜTZT',

    'profile.trustedDevicesTitle': 'Verwaltung Vertrauenswürdiger Geräte',
    'profile.trustedDevicesDesc': 'Aktive Geräte mit Zugriff auf Ihre Oriviant-Wallet',
    'profile.currentDevice': 'AKTUELLES GERÄT',
    'profile.revokeSession': 'Sitzung Widerrufen',

    'profile.loginActivityTitle': 'Letzte Anmeldeaktivitäten',
    'profile.loginActivityDesc': 'Prüfprotokoll der letzten IP-Verbindungen und Geräteautorisierungen',
    'profile.dateTime': 'Datum & Uhrzeit',
    'profile.deviceBrowser': 'Gerät & Browser',
    'profile.location': 'Standort',
    'profile.ipAddress': 'IP-Adresse',
    'profile.status': 'Status',
    'profile.noLoginHistory': 'Noch keine Anmeldeaktivität aufgezeichnet.',

    'profile.preferencesTitle': 'Handelseinstellungen & Lokalisierung',
    'profile.themeMode': 'Design-Modus',
    'profile.darkTheme': 'Dunkles Design',
    'profile.lightTheme': 'Helles Design',
    'profile.language': 'Sprache',
    'profile.displayCurrency': 'Anzeigewährung',
    'profile.savePreferences': 'Einstellungen Speichern',
    'profile.preferencesSaved': 'Einstellungen erfolgreich aktualisiert.',

    'profile.editName': 'Anzeigenamen bearbeiten',
    'profile.changePicture': 'Profilbild ändern',
    'profile.save': 'Speichern',

    'common.signIn': 'Anmelden',
    'common.register': 'Registrieren',
    'common.cancel': 'Abbrechen',
    'common.confirm': 'Bestätigen',
    'common.close': 'Schließen',
    'common.loading': 'Lädt...',

    'header.copyTrading': 'Copy Trading',
    'header.academy': 'Akademie',
    'header.reviews': 'Bewertungen',
    'header.practiceDemoMode': 'Demo-Übungsmodus',
    'header.searchPlaceholder': 'Suchen...',
    'header.searchTooltip': 'Märkte, Coins, Trader suchen (Strg+K)',
    'header.search': 'Suchen',
    'header.notifications': 'Benachrichtigungen',
    'header.accountProfile': 'Kontoprofil & Einstellungen',
    'header.profileAccount': 'Profil & Konto',
    'header.switchToLight': 'Zu Hellem Modus wechseln',
    'header.switchToDark': 'Zu Dunklem Modus wechseln',

    'drawer.accountManagement': 'Kontoverwaltung',
    'drawer.closePanel': 'Kontopanel Schließen',
    'drawer.accountUid': 'Konto-UID',
    'drawer.vipLevel': 'VIP-Stufe',
    'drawer.verification': 'Verifizierung',
    'drawer.kycLevel2': 'KYC Stufe 2',
    'drawer.securityStatus': 'Sicherheitsstatus',
    'drawer.twoFaActive': '2FA Aktiv',
    'drawer.accountVerified': 'Kontoverifizierung: Verifiziert',
    'drawer.dailyLimit': 'Tageslimit: $1.000.000',
    'drawer.themePreference': 'Design-Präferenz',
    'drawer.modeActive': 'Aktiv',
    'drawer.toggleTheme': 'Design Wechseln',
    'drawer.quickActions': 'Schnellzugriff',
    'drawer.myProfile': 'Mein Profil',
    'drawer.myProfileDesc': 'Profil- und Identitätsdaten verwalten',
    'drawer.assets': 'Vermögen',
    'drawer.assetsDesc': 'Guthaben, Ein- und Auszahlungen',
    'drawer.orders': 'Orders',
    'drawer.ordersDesc': 'Aktive Trades & Orderverlauf',
    'drawer.copyTradingDesc': 'Top-Trader und kopierte Portfolios',
    'drawer.settings': 'Einstellungen',
    'drawer.settingsDesc': 'Plattform- und Kontokonfiguration',
    'drawer.security': 'Sicherheit',
    'drawer.securityDesc': '2FA, Passwörter & API-Schlüssel',
    'drawer.notificationsDesc': 'Preisalarme & Aktivitätsupdates',
    'drawer.referralProgram': 'Empfehlungsprogramm (40% verdienen)',
    'drawer.referralDesc': 'Freunde einladen & Provisionen verfolgen',
    'drawer.helpCenter': 'Hilfe-Center & Support',
    'drawer.helpDesc': '24/7-Support & Plattform-Leitfäden',
    'drawer.adminPortal': 'Admin-Portal',
    'drawer.adminDesc': 'Eingeschränkter Administratorzugang',
    'drawer.signOutFull': 'Vom Oriviant-Konto Abmelden',
    'drawer.welcomeExchange': 'Willkommen bei Oriviant Exchange',

    'mobileDrawer.tradingMarkets': 'HANDEL & MÄRKTE',
    'mobileDrawer.homeOverview': 'Startübersicht',
    'mobileDrawer.marketsOverview': 'Marktübersicht',
    'mobileDrawer.spotTrading': 'Spot-Handel',
    'mobileDrawer.futuresTrading': 'Futures-Handel',
    'mobileDrawer.assetsWallets': 'Vermögen & Wallets',
    'mobileDrawer.rewardsEducation': 'BELOHNUNGEN & BILDUNG',
    'mobileDrawer.referralHub': 'Empfehlungs- & Prämienzentrum',
    'mobileDrawer.earn40': '40% verdienen',
    'mobileDrawer.cryptoAcademy': 'Krypto-Akademie & Leitfäden',
    'mobileDrawer.platformReviews': 'Plattformbewertungen',
    'mobileDrawer.accountSupport': 'KONTO & SUPPORT',
    'mobileDrawer.userProfile': 'Benutzerprofil & Verifizierung',
    'mobileDrawer.securitySettings': 'Sicherheit & Einstellungen',
    'mobileDrawer.helpFaq': 'Hilfe-Center & FAQ',
    'mobileDrawer.adminControlPortal': 'Admin-Kontrollportal',
    'mobileDrawer.builtForPerformance': 'Für hohe Leistung entwickelt',

    'welcome.title': 'Willkommen bei Oriviant',
    'welcome.subtitle': 'Handeln Sie Kryptowährungen und globale Märkte auf einer sicheren, schnellen und professionellen Handelsplattform.',
    'welcome.logIn': 'Anmelden',
    'welcome.createAccount': 'Konto Erstellen',
    'welcome.visitWebsite': 'Webseite Besuchen',
    'welcome.support': 'Support',
    'welcome.apkDownloaded': 'APK Heruntergeladen! (v2.4.1)',
    'welcome.downloadingApk': 'APK wird heruntergeladen...',
    'welcome.downloadLatestApk': 'Neueste APK Herunterladen',
    'welcome.ecosystemPreview': 'ÖKOSYSTEM-VORSCHAU',
    'welcome.platformCapabilities': 'Plattformfähigkeiten',
    'welcome.engineeredFor': 'Entwickelt für Hochfrequenzausführung, tiefe Liquidität und institutionelle Sicherheit',
    'welcome.explore': 'Entdecken',
    'welcome.realTimeData': 'ECHTZEITDATEN',
    'welcome.liveMarketPreview': 'Live-Marktvorschau',
    'welcome.guestsMayView': 'Gäste können Live-Preise für Krypto, Rohstoffe, Forex und Aktien einsehen',
    'welcome.asset': 'Vermögenswert',
    'welcome.class': 'Klasse',
    'welcome.price': 'Preis',
    'welcome.change24h': '24-Std-Änderung',
    'welcome.sparkline': 'Verlauf',
    'welcome.action': 'Aktion',
    'welcome.trade': 'Handeln',
    'welcome.reservesTitle': '100% Reservenachweis & Kaltlagerung',
    'welcome.reservesDesc': 'Alle Nutzervermögen sind 1:1 abgesichert mit Echtzeit-Auditierbarkeit und Multi-Signatur-Sicherheit.',
    'welcome.joinToday': 'Jetzt Oriviant Beitreten',
    'welcome.loginRequired': 'Anmeldung Erforderlich',
    'welcome.loginRequiredPrefix': 'Melden Sie sich an oder erstellen Sie ein Konto, um auf',
    'welcome.loginRequiredSuffix': 'bei Oriviant zuzugreifen.',
    'welcome.tradingFeatures': 'Handelsfunktionen',

    'assetClass.crypto': 'Krypto',
    'assetClass.commodities': 'Rohstoffe',
    'assetClass.forex': 'Forex',
    'assetClass.stocks': 'Aktien',

    'welcome.feat1Title': 'Spot-Handel',
    'welcome.feat1Badge': '0,01% Gebühren',
    'welcome.feat1Desc': 'Blitzschnelle Spot-Ausführung auf über 200 Krypto- & Fiat-Paaren mit institutioneller Tiefe.',
    'welcome.feat2Title': 'Futures-Handel',
    'welcome.feat2Badge': 'Bis zu 125x',
    'welcome.feat2Desc': 'Perpetual-Kontrakte mit Cross-/Isolated-Margin und Sub-Millisekunden-Risiko-Engine.',
    'welcome.feat3Title': 'Übungsmodus',
    'welcome.feat3Badge': '10.000 USDT',
    'welcome.feat3Desc': 'Risikofreier Papierhandel mit Live-Marktdaten in Echtzeit und virtuellem Kontobuch.',
    'welcome.feat4Title': 'Copy Trading',
    'welcome.feat4Badge': 'Automatisierter PnL',
    'welcome.feat4Desc': 'Kopieren Sie automatisch Top-Trader oder teilen Sie Strategien, um 40% Gewinnbeteiligung zu verdienen.',
    'welcome.feat5Title': 'Akademie',
    'welcome.feat5Badge': 'Kostenlose Leitfäden',
    'welcome.feat5Desc': 'Meistern Sie technische Analyse, Risikomanagement und Derivatehandelsstrategien.',
    'welcome.feat6Title': 'Sichere Wallet',
    'welcome.feat6Badge': 'Kaltlagerung',
    'welcome.feat6Desc': 'Multi-Signatur-Verwahrung, Anti-Phishing-Schutz und 2FA-Kontosicherheit.',
    'welcome.feat7Title': 'Echtzeitmärkte',
    'welcome.feat7Badge': 'Sub-ms-Ticks',
    'welcome.feat7Desc': 'Streamen Sie Orderbücher, Tiefencharts und Handels-Feeds über globale Anlageklassen.',
    'welcome.feat8Title': 'Erweiterte Charts',
    'welcome.feat8Badge': 'TradingView',
    'welcome.feat8Desc': 'Über 100 technische Indikatoren, Zeichenwerkzeuge und Multi-Zeitrahmen-Analysen.',

    'home.spotTrading': 'Spot-Handel',
    'home.futures125x': 'Futures 125x',
    'home.demoMode': 'Demo-Modus',
    'home.referralHub': 'Empfehlungszentrum',
    'home.fearGreedIndex': 'Krypto Angst-&-Gier-Index',
    'home.updatedAgo': 'Vor 1 Std aktualisiert',
    'home.extremeGreed': 'Extreme Gier',
    'home.sentimentDesc': 'Die Marktstimmung ist stark bullisch. Trader erhöhen aggressiv ihr Long-Engagement bei Layer-1- und KI-Token.',
    'home.topGainers': 'Top-Gewinner 24h',
    'home.viewAll': 'Alle Anzeigen',
    'home.volumeLeaders': 'Volumenführer 24h',
    'home.proCopyTrading': 'PRO COPY TRADING',
    'home.automateProfits': 'Gewinne mit Top-Tradern Automatisieren',
    'home.copyTradesDesc': 'Trades automatisch 1:1 kopieren. Keine manuelle Ausführung nötig.',
    'home.exploreLeadTraders': 'Alle Top-Trader Entdecken',
    'home.copiers': 'Kopierer',
    'home.risk': 'Risiko',
    'home.winRate': 'Gewinnrate',
    'home.aum': 'AUM',
    'home.copyThisTrader': 'Diesen Trader Kopieren',

    'markets.title': 'Multi-Asset-Marktplatz',
    'markets.subtitle': 'Echtzeitkurse für Krypto, Forex, Aktien, ETFs, Indizes, Rohstoffe und Anleihen.',
    'markets.searchPlaceholder': 'Symbol, Namen oder Markt suchen (z.B. AAPL, EUR/USD, Gold)',
    'markets.liveFeedConnected': 'LIVE-DATENFEED VERBUNDEN',
    'markets.latency': 'Latenz',
    'markets.streaming': 'Streaming',
    'markets.markets': 'Märkte',
    'markets.syncEngine': 'Sync-Engine',
    'markets.lastSync': 'Letzte Synchronisierung',
    'markets.syncFeedNow': 'Jetzt Synchronisieren',
    'markets.catAll': 'Alle Märkte',
    'markets.catWatchlist': '★ Watchlist',
    'markets.catCrypto': 'Krypto',
    'markets.catForex': 'Forex',
    'markets.catStocks': 'Aktien',
    'markets.catEtfs': 'ETFs',
    'markets.catIndices': 'Indizes',
    'markets.catCommodities': 'Rohstoffe',
    'markets.catMetals': 'Metalle',
    'markets.catEnergy': 'Energie',
    'markets.catBonds': 'Anleihen',
    'markets.catTrending': '🔥 Trending',
    'markets.catGainers': '📈 Top-Gewinner',
    'markets.catLosers': '📉 Top-Verlierer',
    'markets.catNew': '✨ Neue Listings',
    'markets.catTraded': '⚡ Meistgehandelt',
    'markets.tradingPair': 'Handelspaar',
    'markets.priceUsdt': 'Preis (USDT)',
    'markets.change24h': '24-Std-Änderung',
    'markets.volume24h': '24-Std-Volumen',
    'markets.sparkline7d': 'Verlauf (7T)',
    'markets.actions': 'Aktionen',
    'markets.noCoinsFound': 'Keine Coins gefunden für',
    'markets.spot': 'Spot',
    'markets.futures': 'Futures',

    'auth.welcomeBack': 'Willkommen zurück bei Oriviant',
    'auth.resetPassword': 'Passwort Zurücksetzen',
    'auth.verify2fa': '2FA-Sicherheitscode Verifizieren',
    'auth.createPin': 'Schnellzugriffs-PIN Erstellen',
    'auth.loginSubtitle': 'Zugang zu institutioneller Liquidität und 125x Perpetual Futures',
    'auth.forgotSubtitle': 'Geben Sie Ihre E-Mail ein, um Wiederherstellungsanweisungen zu erhalten',
    'auth.otpSubtitle': 'Geben Sie den 6-stelligen Code ein, der an Ihr Gerät gesendet wurde',
    'auth.pinSubtitle': 'Legen Sie eine 4-stellige Sicherheits-PIN für die schnelle biometrische Anmeldung fest',
    'auth.emailAddress': 'E-Mail-Adresse',
    'auth.password': 'Passwort',
    'auth.forgot': 'Vergessen?',
    'auth.rememberMe': 'Meine Sitzung auf diesem Gerät merken',
    'auth.authenticating': 'Authentifizierung läuft...',
    'auth.signInToAccount': 'Anmelden',
    'auth.sendResetLink': 'Reset-Link Senden',
    'auth.verifySecurityCode': 'Sicherheitscode Verifizieren',
    'auth.saveSecurityPin': 'Sicherheits-PIN Speichern',
    'auth.or': 'ODER',
    'auth.continueWithGoogle': 'Mit Google Fortfahren',
    'auth.noAccount': 'Noch kein Oriviant-Konto?',
    'auth.signUp': 'Registrieren',
    'auth.closeModal': 'Anmeldefenster schließen',
    'auth.showPassword': 'Passwort anzeigen',
    'auth.hidePassword': 'Passwort verbergen',

    'signup.exchange': 'ORIVIANT EXCHANGE',
    'signup.createAccount': 'Konto Erstellen',
    'signup.tagline': 'Trade • Invest • Grow',
    'signup.joinDesc': 'Schließen Sie sich Tausenden von Tradern weltweit an und beginnen Sie noch heute Ihre Handelsreise.',
    'signup.fullName': 'Vollständiger Name',
    'signup.fullNameRequired': 'Vollständiger Name ist erforderlich',
    'signup.fullNameMin': 'Mindestens 2 Zeichen erforderlich',
    'signup.emailRequired': 'E-Mail-Adresse ist erforderlich',
    'signup.emailInvalid': 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
    'signup.emailTaken': 'Diese E-Mail-Adresse ist bereits registriert.',
    'signup.phoneNumber': 'Telefonnummer',
    'signup.autoDetected': 'Automatisch erkannt',
    'signup.phoneRequired': 'Telefonnummer ist erforderlich',
    'signup.phoneInvalid': 'Bitte geben Sie eine gültige Telefonnummer ein',
    'signup.phoneTaken': 'Diese Telefonnummer ist bereits registriert.',
    'signup.searchCountry': 'Land oder Vorwahl suchen...',
    'signup.noMatchingCountry': 'Kein passendes Land gefunden',
    'signup.password': 'Passwort',
    'signup.strength': 'Stärke',
    'signup.strengthWeak': 'Schwach',
    'signup.strengthFair': 'Mäßig',
    'signup.strengthGood': 'Gut',
    'signup.strengthStrong': 'Stark',
    'signup.min8Chars': 'Mind. 8 Zeichen',
    'signup.uppercaseLetter': 'Großbuchstabe',
    'signup.lowercaseLetter': 'Kleinbuchstabe',
    'signup.oneNumber': 'Eine Zahl',
    'signup.oneSpecialChar': 'Ein Sonderzeichen (!@#$%)',
    'signup.confirmPassword': 'Passwort Bestätigen',
    'signup.passwordsMatch': 'Passwörter Stimmen Überein',
    'signup.passwordsNoMatch': 'Passwörter Stimmen Nicht Überein',
    'signup.reenterPassword': 'Passwort erneut eingeben',
    'signup.haveReferralCode': 'Haben Sie einen Empfehlungscode?',
    'signup.enterCode': 'Code eingeben (z.B. ORV894)',
    'signup.referralBonus': 'Erhalten Sie 10% Gebührenrabatt und einen 100$-Bonusgutschein bei Einzahlung.',
    'signup.imHuman': 'Ich bin ein Mensch (Sicherheitsüberprüfung)',
    'signup.agreeTermsPrefix': 'Ich stimme den',
    'signup.termsOfService': 'Nutzungsbedingungen',
    'signup.and': 'und der',
    'signup.privacyPolicy': 'Datenschutzrichtlinie',
    'signup.receiveUpdates': 'Handelsupdates, Plattformnachrichten und Aktionen erhalten.',
    'signup.creatingAccount': 'Konto wird erstellt...',
    'signup.alreadyHaveAccount': 'Haben Sie bereits ein Konto?',
    'signup.registrationFailed': 'Registrierung fehlgeschlagen. Die E-Mail wird möglicherweise bereits verwendet oder der Server ist nicht erreichbar.',
    'signup.accountCreated': 'Konto Erfolgreich Erstellt!',
    'signup.verificationSentPrefix': 'Wir haben eine Bestätigungs-E-Mail gesendet an',
    'signup.verificationSentSuffix': 'Bitte bestätigen Sie Ihre E-Mail, bevor Sie auf Ihr Konto zugreifen.',
    'signup.verificationInstructions': 'Bestätigungsanweisungen',
    'signup.instructionsLine1': '1. Prüfen Sie Ihren Posteingang auf die Nachricht von Oriviant Security.',
    'signup.instructionsLine2': '2. Klicken Sie auf den sicheren Bestätigungslink darin.',
    'signup.instructionsLine3': '3. Kehren Sie hierher zurück oder melden Sie sich an, um auf Ihr 10.000-USDT-Übungsguthaben und Live-Märkte zuzugreifen.',
    'signup.openEmailApp': 'E-Mail-App Öffnen',
    'signup.resendEmail': 'E-Mail Erneut Senden',
    'signup.resendCountdown': 'Erneut senden',
    'signup.changeEmail': 'E-Mail Ändern',
    'signup.proceedToLogin': 'Weiter zu Anmeldung & Dashboard',
    'signup.resendDispatched': 'Eine neue Bestätigungs-E-Mail wurde gesendet!',

    'wallet.vaultBadge': 'ORIVIANT ENTERPRISE VAULT',
    'wallet.frozen': 'WALLET EINGEFROREN',
    'wallet.title': 'Wallet- & Vermögensverwaltung',
    'wallet.subtitle': 'Multi-Chain-Einzahlungen, institutionelle Cold-Storage-Auszahlungen und interne Überweisungen.',
    'wallet.deposit': 'Einzahlen',
    'wallet.withdraw': 'Auszahlen',
    'wallet.transfer': 'Überweisen',
    'wallet.addressBook': 'Adressbuch',
    'wallet.balance': 'GUTHABEN',
    'wallet.totalAvailable': 'Gesamt Verfügbar',
    'wallet.readyForTrading': 'Bereit für Handel / Auszahlung',
    'wallet.lockedFrozen': 'Gesperrt / Eingefroren',
    'wallet.pendingOrders': 'Ausstehende Orders & Auszahlungen',
    'wallet.unrealizedPnl': 'Unrealisierter PnL',
    'wallet.openFuturesPositions': 'Offene Futures-Positionen',
    'wallet.accountTier': 'Kontostufe',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.markets': 'マーケット',
    'nav.futures': '先物',
    'nav.spot': '現物',
    'nav.assets': '資産',

    'profile.signOut': 'サインアウト',
    'profile.practiceDemo': 'デモ練習ワークスペース',
    'profile.verified': 'レベル2 エンタープライズ認証済み',
    'profile.securityScoreTitle': 'セキュリティ保護スコア',
    'profile.highlySecured': '高度に保護',
    'profile.securityScoreDesc': 'あなたのアカウントは2FA、メール認証、ホワイトリストアドレス、フィッシング対策で保護されています。',

    'profile.suiteTitle': 'アカウントセキュリティ・認証スイート',
    'profile.suiteDesc': '多層認証とフィッシング対策',
    'profile.emailVerification': 'メール認証',
    'profile.verifiedBadge': '認証済み',
    'profile.emailNote': 'すべての出金とパスワード変更に必要です。',
    'profile.googleAuth': 'Google Authenticator 2FA',
    'profile.active': '有効',
    'profile.totpNote': 'TOTP時間ベースセキュリティトークン有効',
    'profile.protectsNote': '不正な出金から資金を保護します。',
    'profile.passkey': '生体認証パスキー',
    'profile.hardwareReady': 'ハードウェア対応',
    'profile.passkeyNote': 'FaceID / TouchID / FIDO2キー',
    'profile.nextGenNote': '次世代パスワードレスセキュリティオプション。',

    'profile.antiPhishingTitle': 'カスタムフィッシング対策コード',
    'profile.antiPhishingDesc': 'このコードはOriviantから送信されるすべての公式通知メールに埋め込まれ、なりすましやフィッシングを防ぎます。',
    'profile.changeCode': 'コードを変更',
    'profile.saveCode': 'コードを保存',
    'profile.protected': '保護済み',

    'profile.trustedDevicesTitle': '信頼済みデバイス管理',
    'profile.trustedDevicesDesc': 'Oriviantウォレットへのアクセスを許可されているアクティブなデバイス',
    'profile.currentDevice': '現在のデバイス',
    'profile.revokeSession': 'セッションを無効化',

    'profile.loginActivityTitle': '最近のログインアクティビティ',
    'profile.loginActivityDesc': '最近のIP接続とデバイス認証の監査記録',
    'profile.dateTime': '日時',
    'profile.deviceBrowser': 'デバイスとブラウザ',
    'profile.location': '場所',
    'profile.ipAddress': 'IPアドレス',
    'profile.status': 'ステータス',
    'profile.noLoginHistory': 'まだログインアクティビティが記録されていません。',

    'profile.preferencesTitle': '取引設定とローカライズ',
    'profile.themeMode': 'テーマモード',
    'profile.darkTheme': 'ダークテーマ',
    'profile.lightTheme': 'ライトテーマ',
    'profile.language': '言語',
    'profile.displayCurrency': '表示通貨',
    'profile.savePreferences': '設定を保存',
    'profile.preferencesSaved': '設定が正常に更新されました。',

    'profile.editName': '表示名を編集',
    'profile.changePicture': 'プロフィール画像を変更',
    'profile.save': '保存',

    'common.signIn': 'サインイン',
    'common.register': '登録',
    'common.cancel': 'キャンセル',
    'common.confirm': '確認',
    'common.close': '閉じる',
    'common.loading': '読み込み中...',

    'header.copyTrading': 'コピートレード',
    'header.academy': 'アカデミー',
    'header.reviews': 'レビュー',
    'header.practiceDemoMode': 'デモ練習モード',
    'header.searchPlaceholder': '検索...',
    'header.searchTooltip': 'マーケット、コイン、トレーダーを検索 (Ctrl+K)',
    'header.search': '検索',
    'header.notifications': '通知',
    'header.accountProfile': 'アカウントプロフィールと設定',
    'header.profileAccount': 'プロフィールとアカウント',
    'header.switchToLight': 'ライトモードに切り替え',
    'header.switchToDark': 'ダークモードに切り替え',

    'drawer.accountManagement': 'アカウント管理',
    'drawer.closePanel': 'アカウントパネルを閉じる',
    'drawer.accountUid': 'アカウントUID',
    'drawer.vipLevel': 'VIPレベル',
    'drawer.verification': '認証',
    'drawer.kycLevel2': 'KYCレベル2',
    'drawer.securityStatus': 'セキュリティステータス',
    'drawer.twoFaActive': '2FA有効',
    'drawer.accountVerified': 'アカウント認証：認証済み',
    'drawer.dailyLimit': '1日の上限：$1,000,000',
    'drawer.themePreference': 'テーマ設定',
    'drawer.modeActive': '有効',
    'drawer.toggleTheme': 'テーマを切り替え',
    'drawer.quickActions': 'クイックアクション',
    'drawer.myProfile': 'マイプロフィール',
    'drawer.myProfileDesc': 'プロフィールと身元情報を管理',
    'drawer.assets': '資産',
    'drawer.assetsDesc': '残高、入金と出金',
    'drawer.orders': '注文',
    'drawer.ordersDesc': 'アクティブな取引と注文履歴',
    'drawer.copyTradingDesc': 'リードトレーダーとコピーしたポートフォリオ',
    'drawer.settings': '設定',
    'drawer.settingsDesc': 'プラットフォームとアカウントの設定',
    'drawer.security': 'セキュリティ',
    'drawer.securityDesc': '2FA、パスワード、APIキー',
    'drawer.notificationsDesc': '価格アラートとアクティビティ更新',
    'drawer.referralProgram': '紹介プログラム（40%獲得）',
    'drawer.referralDesc': '友達を招待して報酬を追跡',
    'drawer.helpCenter': 'ヘルプセンターとサポート',
    'drawer.helpDesc': '24時間サポートとプラットフォームガイド',
    'drawer.adminPortal': '管理者ポータル',
    'drawer.adminDesc': '制限された管理者アクセス',
    'drawer.signOutFull': 'Oriviantアカウントからサインアウト',
    'drawer.welcomeExchange': 'Oriviant Exchangeへようこそ',

    'mobileDrawer.tradingMarkets': '取引とマーケット',
    'mobileDrawer.homeOverview': 'ホーム概要',
    'mobileDrawer.marketsOverview': 'マーケット概要',
    'mobileDrawer.spotTrading': '現物取引',
    'mobileDrawer.futuresTrading': '先物取引',
    'mobileDrawer.assetsWallets': '資産とウォレット',
    'mobileDrawer.rewardsEducation': '報酬と教育',
    'mobileDrawer.referralHub': '紹介・報酬ハブ',
    'mobileDrawer.earn40': '40%獲得',
    'mobileDrawer.cryptoAcademy': '暗号資産アカデミーとガイド',
    'mobileDrawer.platformReviews': 'プラットフォームレビューと評価',
    'mobileDrawer.accountSupport': 'アカウントとサポート',
    'mobileDrawer.userProfile': 'ユーザープロフィールと認証',
    'mobileDrawer.securitySettings': 'セキュリティと設定',
    'mobileDrawer.helpFaq': 'ヘルプセンターとFAQ',
    'mobileDrawer.adminControlPortal': '管理コントロールポータル',
    'mobileDrawer.builtForPerformance': '高性能のために構築',

    'welcome.title': 'Oriviantへようこそ',
    'welcome.subtitle': '安全で高速なプロフェッショナル取引プラットフォームで、暗号資産とグローバル市場を取引しましょう。',
    'welcome.logIn': 'ログイン',
    'welcome.createAccount': 'アカウント作成',
    'welcome.visitWebsite': 'ウェブサイトを見る',
    'welcome.support': 'サポート',
    'welcome.apkDownloaded': 'APKダウンロード完了！(v2.4.1)',
    'welcome.downloadingApk': 'APKをダウンロード中...',
    'welcome.downloadLatestApk': '最新のAPKをダウンロード',
    'welcome.ecosystemPreview': 'エコシステムプレビュー',
    'welcome.platformCapabilities': 'プラットフォーム機能',
    'welcome.engineeredFor': '高頻度実行、深い流動性、機関レベルのセキュリティのために設計',
    'welcome.explore': '詳しく見る',
    'welcome.realTimeData': 'リアルタイムデータ',
    'welcome.liveMarketPreview': 'ライブマーケットプレビュー',
    'welcome.guestsMayView': 'ゲストは暗号資産、コモディティ、外国為替、株式のライブ価格を閲覧できます',
    'welcome.asset': '資産',
    'welcome.class': '種別',
    'welcome.price': '価格',
    'welcome.change24h': '24時間変動',
    'welcome.sparkline': 'チャート',
    'welcome.action': '操作',
    'welcome.trade': '取引',
    'welcome.reservesTitle': '100%準備金証明とコールドストレージ',
    'welcome.reservesDesc': 'すべてのユーザー資産は1:1で裏付けられ、リアルタイム監査とマルチシグセキュリティで保護されています。',
    'welcome.joinToday': '今すぐOriviantに参加',
    'welcome.loginRequired': 'ログインが必要です',
    'welcome.loginRequiredPrefix': 'Oriviantで',
    'welcome.loginRequiredSuffix': 'にアクセスするには、サインインまたはアカウントを作成してください。',
    'welcome.tradingFeatures': '取引機能',

    'assetClass.crypto': '暗号資産',
    'assetClass.commodities': 'コモディティ',
    'assetClass.forex': '外国為替',
    'assetClass.stocks': '株式',

    'welcome.feat1Title': '現物取引',
    'welcome.feat1Badge': '0.01%手数料',
    'welcome.feat1Desc': '200以上の暗号資産・法定通貨ペアで機関レベルの深さを持つ超高速現物取引。',
    'welcome.feat2Title': '先物取引',
    'welcome.feat2Badge': '最大125倍',
    'welcome.feat2Desc': 'クロス/分離証拠金対応の無期限契約とミリ秒未満のリスクエンジン。',
    'welcome.feat3Title': '練習モード',
    'welcome.feat3Badge': '10,000 USDT',
    'welcome.feat3Desc': 'リアルタイム市場データと仮想台帳を備えたリスクフリーの模擬取引デスク。',
    'welcome.feat4Title': 'コピートレード',
    'welcome.feat4Badge': '自動損益',
    'welcome.feat4Desc': 'トップトレーダーを自動でコピー、または戦略を共有して利益の40%を獲得。',
    'welcome.feat5Title': 'アカデミー',
    'welcome.feat5Badge': '無料ガイド',
    'welcome.feat5Desc': 'テクニカル分析、リスク管理、デリバティブ取引の枠組みを習得。',
    'welcome.feat6Title': '安全なウォレット',
    'welcome.feat6Badge': 'コールドストレージ',
    'welcome.feat6Desc': 'マルチシグ管理、フィッシング対策、2FAアカウント保護。',
    'welcome.feat7Title': 'リアルタイムマーケット',
    'welcome.feat7Badge': 'ミリ秒未満のティック',
    'welcome.feat7Desc': 'グローバル資産クラス全体の板情報、深度チャート、取引フィードを配信。',
    'welcome.feat8Title': '高度なチャート',
    'welcome.feat8Badge': 'TradingView',
    'welcome.feat8Desc': '100以上のテクニカル指標、描画ツール、マルチタイムフレーム分析。',

    'home.spotTrading': '現物取引',
    'home.futures125x': '先物125倍',
    'home.demoMode': 'デモモード',
    'home.referralHub': '紹介ハブ',
    'home.fearGreedIndex': '暗号資産 恐怖と強欲指数',
    'home.updatedAgo': '1時間前に更新',
    'home.extremeGreed': '極度の強欲',
    'home.sentimentDesc': '市場センチメントは非常に強気です。トレーダーはレイヤー1およびAIトークンでロングポジションを積極的に増やしています。',
    'home.topGainers': '24時間の値上がり上位',
    'home.viewAll': 'すべて見る',
    'home.volumeLeaders': '24時間出来高上位',
    'home.proCopyTrading': 'プロコピートレード',
    'home.automateProfits': 'トップトレーダーで利益を自動化',
    'home.copyTradesDesc': '取引を自動的に1:1でコピー。手動実行は不要です。',
    'home.exploreLeadTraders': 'すべてのリードトレーダーを見る',
    'home.copiers': 'コピー数',
    'home.risk': 'リスク',
    'home.winRate': '勝率',
    'home.aum': '運用資産',
    'home.copyThisTrader': 'このトレーダーをコピー',

    'markets.title': 'マルチアセットマーケット',
    'markets.subtitle': '暗号資産、外国為替、株式、ETF、指数、コモディティ、債券のリアルタイム相場。',
    'markets.searchPlaceholder': 'シンボル、名前、マーケットを検索（例：AAPL、EUR/USD、金）',
    'markets.liveFeedConnected': 'ライブデータフィード接続中',
    'markets.latency': '遅延',
    'markets.streaming': '配信中',
    'markets.markets': 'マーケット',
    'markets.syncEngine': '同期エンジン',
    'markets.lastSync': '最終同期',
    'markets.syncFeedNow': '今すぐ同期',
    'markets.catAll': 'すべてのマーケット',
    'markets.catWatchlist': '★ ウォッチリスト',
    'markets.catCrypto': '暗号資産',
    'markets.catForex': '外国為替',
    'markets.catStocks': '株式',
    'markets.catEtfs': 'ETF',
    'markets.catIndices': '指数',
    'markets.catCommodities': 'コモディティ',
    'markets.catMetals': '金属',
    'markets.catEnergy': 'エネルギー',
    'markets.catBonds': '債券',
    'markets.catTrending': '🔥 トレンド',
    'markets.catGainers': '📈 値上がり上位',
    'markets.catLosers': '📉 値下がり上位',
    'markets.catNew': '✨ 新規上場',
    'markets.catTraded': '⚡ 取引量上位',
    'markets.tradingPair': '取引ペア',
    'markets.priceUsdt': '価格 (USDT)',
    'markets.change24h': '24時間変動',
    'markets.volume24h': '24時間出来高',
    'markets.sparkline7d': 'チャート（7日）',
    'markets.actions': '操作',
    'markets.noCoinsFound': '一致する銘柄が見つかりません',
    'markets.spot': '現物',
    'markets.futures': '先物',

    'auth.welcomeBack': 'Oriviantへおかえりなさい',
    'auth.resetPassword': 'パスワードをリセット',
    'auth.verify2fa': '2FAセキュリティコードを確認',
    'auth.createPin': 'クイックアクセスPINを作成',
    'auth.loginSubtitle': '機関投資家レベルの流動性と125倍の無期限先物にアクセス',
    'auth.forgotSubtitle': '回復手順を受け取るにはメールアドレスを入力してください',
    'auth.otpSubtitle': 'デバイスに送信された6桁の確認コードを入力してください',
    'auth.pinSubtitle': '生体認証によるクイックサインイン用の4桁のセキュリティPINを設定',
    'auth.emailAddress': 'メールアドレス',
    'auth.password': 'パスワード',
    'auth.forgot': 'お忘れですか？',
    'auth.rememberMe': 'このデバイスでのセッションを記憶する',
    'auth.authenticating': '認証中...',
    'auth.signInToAccount': 'サインイン',
    'auth.sendResetLink': 'リセットリンクを送信',
    'auth.verifySecurityCode': 'セキュリティコードを確認',
    'auth.saveSecurityPin': 'セキュリティPINを保存',
    'auth.or': 'または',
    'auth.continueWithGoogle': 'Googleで続ける',
    'auth.noAccount': 'Oriviantアカウントをお持ちでないですか？',
    'auth.signUp': 'サインアップ',
    'auth.closeModal': '認証ウィンドウを閉じる',
    'auth.showPassword': 'パスワードを表示',
    'auth.hidePassword': 'パスワードを隠す',

    'signup.exchange': 'ORIVIANT EXCHANGE',
    'signup.createAccount': 'アカウントを作成',
    'signup.tagline': 'Trade • Invest • Grow',
    'signup.joinDesc': '世界中の何千人ものトレーダーに参加し、今すぐ取引の旅を始めましょう。',
    'signup.fullName': '氏名',
    'signup.fullNameRequired': '氏名は必須です',
    'signup.fullNameMin': '最低2文字必要です',
    'signup.emailRequired': 'メールアドレスは必須です',
    'signup.emailInvalid': '有効なメールアドレスを入力してください',
    'signup.emailTaken': 'このメールアドレスは既に登録されています。',
    'signup.phoneNumber': '電話番号',
    'signup.autoDetected': '自動検出',
    'signup.phoneRequired': '電話番号は必須です',
    'signup.phoneInvalid': '有効な電話番号を入力してください',
    'signup.phoneTaken': 'この電話番号は既に登録されています。',
    'signup.searchCountry': '国または国番号を検索...',
    'signup.noMatchingCountry': '一致する国が見つかりません',
    'signup.password': 'パスワード',
    'signup.strength': '強度',
    'signup.strengthWeak': '弱い',
    'signup.strengthFair': '普通',
    'signup.strengthGood': '良い',
    'signup.strengthStrong': '強い',
    'signup.min8Chars': '最低8文字',
    'signup.uppercaseLetter': '大文字',
    'signup.lowercaseLetter': '小文字',
    'signup.oneNumber': '数字を1つ',
    'signup.oneSpecialChar': '特殊文字を1つ (!@#$%)',
    'signup.confirmPassword': 'パスワードの確認',
    'signup.passwordsMatch': 'パスワードが一致しています',
    'signup.passwordsNoMatch': 'パスワードが一致しません',
    'signup.reenterPassword': 'パスワードを再入力',
    'signup.haveReferralCode': '紹介コードをお持ちですか？',
    'signup.enterCode': 'コードを入力（例：ORV894）',
    'signup.referralBonus': '入金時に手数料10%割引と100ドルのボーナスクーポンを獲得。',
    'signup.imHuman': '私は人間です（セキュリティ認証）',
    'signup.agreeTermsPrefix': '私は',
    'signup.termsOfService': '利用規約',
    'signup.and': 'と',
    'signup.privacyPolicy': 'プライバシーポリシー',
    'signup.receiveUpdates': '取引アップデート、プラットフォームニュース、プロモーションを受け取る。',
    'signup.creatingAccount': 'アカウント作成中...',
    'signup.alreadyHaveAccount': 'すでにアカウントをお持ちですか？',
    'signup.registrationFailed': '登録に失敗しました。メールアドレスが既に使用されているか、サーバーに接続できません。',
    'signup.accountCreated': 'アカウントが作成されました！',
    'signup.verificationSentPrefix': '確認メールを送信しました：',
    'signup.verificationSentSuffix': 'アカウントにアクセスする前にメールを確認してください。',
    'signup.verificationInstructions': '確認手順',
    'signup.instructionsLine1': '1. Oriviant Securityからのメッセージを受信箱で確認してください。',
    'signup.instructionsLine2': '2. メール内の安全な確認リンクをクリックしてください。',
    'signup.instructionsLine3': '3. ここに戻るか、ログインして10,000 USDTの練習残高とライブマーケットにアクセスしてください。',
    'signup.openEmailApp': 'メールアプリを開く',
    'signup.resendEmail': 'メールを再送信',
    'signup.resendCountdown': '再送信',
    'signup.changeEmail': 'メールを変更',
    'signup.proceedToLogin': 'サインインとダッシュボードへ進む',
    'signup.resendDispatched': '新しい確認メールを送信しました！',

    'wallet.vaultBadge': 'Oriviantエンタープライズボールト',
    'wallet.frozen': 'ウォレット凍結中',
    'wallet.title': 'ウォレットと資産管理',
    'wallet.subtitle': 'マルチチェーン入金、機関レベルのコールドストレージ出金、内部送金。',
    'wallet.deposit': '入金',
    'wallet.withdraw': '出金',
    'wallet.transfer': '送金',
    'wallet.addressBook': 'アドレス帳',
    'wallet.balance': '残高',
    'wallet.totalAvailable': '利用可能合計',
    'wallet.readyForTrading': '取引・出金可能',
    'wallet.lockedFrozen': 'ロック中/凍結中',
    'wallet.pendingOrders': '保留中の注文・出金',
    'wallet.unrealizedPnl': '未実現損益',
    'wallet.openFuturesPositions': '未決済の先物ポジション',
    'wallet.accountTier': 'アカウントティア',
  }
} as const;

interface LocalizationContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  currency: CurrencyCode;
  setCurrency: (cur: CurrencyCode) => void;
  t: (key: TranslationKey) => string;
  formatCurrency: (usdAmount: number, options?: Intl.NumberFormatOptions) => string;
}

const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'oriviant_language';
const CURRENCY_STORAGE_KEY = 'oriviant_currency';

const readStoredLanguage = (): LanguageCode => {
  const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return stored && stored in TRANSLATIONS ? (stored as LanguageCode) : 'en';
};

const readStoredCurrency = (): CurrencyCode => {
  const stored = localStorage.getItem(CURRENCY_STORAGE_KEY);
  return stored && stored in CURRENCY_RATES ? (stored as CurrencyCode) : 'USD';
};

export const LocalizationProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(readStoredLanguage);
  const [currency, setCurrencyState] = useState<CurrencyCode>(readStoredCurrency);

  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem(CURRENCY_STORAGE_KEY, currency);
  }, [currency]);

  const setLanguage = (lang: LanguageCode) => setLanguageState(lang);
  const setCurrency = (cur: CurrencyCode) => setCurrencyState(cur);

  const t = (key: TranslationKey): string => {
    return (TRANSLATIONS[language] as Record<string, string>)[key] ?? TRANSLATIONS.en[key] ?? key;
  };

  const formatCurrency = (usdAmount: number, options?: Intl.NumberFormatOptions): string => {
    const converted = (usdAmount || 0) * CURRENCY_RATES[currency];
    try {
      return new Intl.NumberFormat(CURRENCY_LOCALE[currency], {
        style: 'currency',
        currency,
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
        ...options
      }).format(converted);
    } catch {
      return `${CURRENCY_OPTIONS.find((c) => c.code === currency)?.symbol ?? '$'}${converted.toFixed(2)}`;
    }
  };

  return (
    <LocalizationContext.Provider value={{ language, setLanguage, currency, setCurrency, t, formatCurrency }}>
      {children}
    </LocalizationContext.Provider>
  );
};

export const useLocalization = () => {
  const context = useContext(LocalizationContext);
  if (!context) throw new Error('useLocalization must be used within a LocalizationProvider');
  return context;
};
